---
test:
  ibm_cloud_power_defaults: &ibm_cloud_power_defaults
    api_key: IBM_CLOUD_POWERVS_API_KEY
  ibm_cloud_power:
    <<: *ibm_cloud_power_defaults
  ibm_cloud_vpc_defaults: &ibm_cloud_vpc_defaults
    api_key: IBM_CLOUD_VPC_API_KEY
  ibm_cloud_vpc:
    <<: *ibm_cloud_vpc_defaults
