:ems:
  :ems_ibm_cloud_power_virtual_servers:
    :api_endpoint_overrides:
      :dal12: us-south.power-iaas.cloud.ibm.com
    :event_handling:
      :event_groups:
        :power:
          :critical:
          - IBM_CLOUD_POWER_VIRTUAL_SERVERS_instance_power_on
          - IBM_CLOUD_POWER_VIRTUAL_SERVERS_instance_power_off
  :ems_ibm_cloud_vpc:
    :event_handling:
      :event_groups:
        :addition:
          :critical:
          - is.instance.instance.create
          - is.instance.action.create
          - is.instance.console-access-token.create
          - is.instance.volume-attachment.create
          - is.instance.network-interface.create
        :update:
          :critical:
          - is.instance.instance.update
          - is.instance.instance.read
          - is.instance.console.read
          - is.instance.network-interface_floating-ip.attach
          - is.instance.network-interface_floating-ip.detach
          - is.instance.volume-attachment.update
          - is.instance.volume-attachment.read
          - is.instance.network-interface.update
          - is.instance.network-interface.read
          - is.instance.network-interface_floating-ip.read
          - is.instance.disk.read
          - is.instance.disk.update
        :deletion:
          :critical:
          - is.instance.instance.delete
          - is.instance.action.delete
          - is.instance.volume-attachment.delete
          - is.instance.network-interface.delete
          - is.instance.disk.wipe
          - is.instance.gpu.wipe
        :power:
          :critical:
          - is.instance.instance.start
          - is.instance.instance.stop
          - is.instance.instance.volume-stop

:ems_refresh:
  :ibm_vpc:
    :refresh_interval: 15.minutes
    :allow_targeted_refresh: true
  :ibm_cloud_power_virtual_servers:
    :refresh_interval: 15.minutes
:log:
  :level_ibm_cloud: info
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_ibm_cloud_power_virtual_servers:
        :poll: 20.seconds
      :event_catcher_vpc:
        :poll: 15.seconds
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_ibm_cloud_power_virtual_servers: {}
        :ems_refresh_worker_ibm_cloud_vpc: {}
