:ems:
  :ems_ibm_cloud_power_virtual_servers:
    :api_endpoint_overrides:
      :dal12: us-south.power-iaas.cloud.ibm.com
    :event_handling:
      :event_groups:
        :power:
          :critical:
          - IBM_CLOUD_POWER_VIRTUAL_SERVERS_instance_power_on
          - IBM_CLOUD_POWER_VIRTUAL_SERVERS_instance_power_off
  :ems_ibm_cloud_vpc:
    :event_handling:
      :event_groups:
        :addition:
          :critical:
          - is.instance.instance.create

:ems_refresh:
  :ibm_vpc:
    :refresh_interval: 15.minutes
    :allow_targeted_refresh: true
  :ibm_cloud_power_virtual_servers:
    :refresh_interval: 15.minutes
:log:
  :level_ibm_cloud: info
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_ibm_cloud_power_virtual_servers:
        :poll: 20.seconds
      :event_catcher_vpc:
        :poll: 15.seconds
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_ibm_cloud_power_virtual_servers: {}
        :ems_refresh_worker_ibm_cloud_vpc: {}
